### ISSUE TITLE
Load pgn Error

### ISSUE THREAD

**Issue by al75an** [Bernton/BerldChess#5]
Hi Brenton,
Thank you very much for the cool and simple app
I am getting an error when trying to download the game from pgn
all the settings are the default
any suggestions?
Greetings
Alan

**Comment by Bernton** [comment]
Hello @al75an , can you maybe give me more information about the error? Is there an error message? Does no PGN work or only a particular one?

**Comment by al75an** [comment]
Hi ,
Thank you for taking the time to respond
The error happens before even choosing the pgn file right after clicking on load from pgn
[cid:image002.jpg@01D50FD8.BE7997D0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by al75an** [comment]
Hi Bernton,
Here is a picture of the error and like said before the error happens before even choosing the pgn file
[cid:image003.jpg@01D50FDA.35FC6C00]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Bernton** [comment]
I can't view the images. @al75an

**Comment by al75an** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by al75an** [comment]
[cid:339b727a-2177-4f17-9518-c07768d7cb99]
________________________________

**Comment by Bernton** [comment]
The E-Mail reply with image attachment doesn't work on GitHub. @al75an , all I see is "[cid:339b727a-2177-4f17-9518-c07768d7cb99]"

**Comment by al75an** [comment]
Hi Brenton,
I upload the image to Drop Box:
https://www.dropbox.com/s/mp51nm162ab6r67/2.jpg?dl=0

greetings
Alan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Bernton** [comment]
Oh, there is simply a dll missing in the release build, I will update the release soon, else you can use the source directly and build it with Visual Studio for example, or wait for the update. @al75an

**Comment by Bernton** [comment]
@al75an Here is the new release which should work: https://github.com/Bernton/BerldChess/releases/tag/1.6

**Comment by al75an** [comment]
Hi Bernton,
I get error after choosing pgn file (all pgn same problem) and the version shows 1.5 on the top left corner should be 1.6
Please check the image by clicking the link bellow
https://www.dropbox.com/s/0j0myj5m9ur9nd8/ber.jpg?dl=0

greetings
Alan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Bernton** [comment]
You are missing the windows FSharp redist, FSharp.Core.dll is on the directory right? Maybe this helps: https://stackoverflow.com/questions/3042253/could-not-load-file-or-assembly-fsharp-core-version-4-0-0-0

**Comment by Bernton** [comment]
Redist here: https://www.microsoft.com/en-us/download/details.aspx?id=13450
Kinda weird, it should come with the normal windows updates.

**Comment by al75an** [comment]
Hi,
It did not work all pgn and all pc even after installing  Microsoft Visual Studio 2010 F# Runtime 2.0
https://www.dropbox.com/s/y1489gw0cy0gphq/33.jpg?dl=0

my system os is  windows 10 64 bit
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Bernton** [comment]
Ok, try this setup, maybe you're missing a windows framework: https://github.com/Bernton/BerldChess/releases/download/1.6/Release_setup.zip

**Comment by al75an** [comment]
Thank you, Awesome News It is working now

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by al75an** [comment]
Berld chess is light, fast and easy way to analyze your game
thank you Brenton

**Comment by Bernton** [comment]
There is a new version (1.7) available, uninstall the old and install this (visual bug with arrows fixed): https://github.com/Bernton/BerldChess/releases/tag/1.7 @al75an

**Comment by al75an** [comment]
Awesome, Thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Bernton** [comment]
It should say Version 1.7 now, is that true? @al75an

**Comment by al75an** [comment]
Awesome, Yes It is showing Version 1.7 now.
Could you please, consider multiple games  pgn support in the future updates

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
